import Head from 'next/head'
import Image from 'next/image'

import qr from '../public/image-qr-code.png'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className='container'>
        <section className='card'>
          <div className='card-image' >
            <Image src={qr} alt='qr code' width={qr.width} height={qr.height}/>
          </div>
          <div className='card-content'>
            <h1 className='text-center'>Improve your front-end skills by building projects </h1>
            <p className='text-center'>Scan the QR code to visit Frontend Mentor and take your coding skills to the next level</p>
          </div>
        </section>
      </main>
    </>
  )
}
