import Head from 'next/head'
import qr from '../public/image-qr-code.png'
import { Card } from '@/components/Card'


export default function Home() {
  return (
    <>
      <Head>
        <title>QR code component solution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="QR code component solution" />
        <meta property="og:description" content="Generated by create next app" />
        <meta property="og:image" content="/screenshot.png" />
        <meta property="og:url" content="https://fm-qr-code-mad.vercel.app/" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className='container'>
        <Card qr={qr}/>
      </main>
    </>
  )
}
